name: My-githubActions
env:
  APPLICATION_NAME: "MyFlask"
  DEPLOY_PACKAGE_NAME: "flask-deploy-ver-${{ github.sha }}"

on: 
  push:
     branches:  
       - main

jobs:
  my_testing:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message in testing
        run: echo "Hellow World from Testing job" 
    
 
